sonar.projectKey=sb05-monew-team1:monew-app
sonar.projectName=monew-app
sonar.sourceEncoding=UTF-8
sonar.organization=sb05-monew-team1

# Paths
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=build/classes/java/main

# Reports
sonar.junit.reportPaths=build/test-results/test
sonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/test/jacocoTestReport.xml

# Exclusions
sonar.coverage.exclusions=**/generated/**, **/Q**.java, **/build/**, **/*MapperImpl.java, **/config/**/Test*/**, **/fixture/**