spring:
  profiles:
    active: prod # dev | prod
  config:
    import: optional:file:.env[.properties]

monew:
  storage:
    s3:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
      region: ${AWS_S3_REGION}
      bucket: ${AWS_S3_BUCKET}
      expiration: ${AWS_S3_PRESIGNED_URL_EXPIRATION:600}

management:
  endpoint:
    health:
      probes:
        enabled: true   # readiness/liveness 사용시
  metrics:
    tags:
      application: app

server:
  port: 8080 # app / 8081 # batch
  servlet:
    session:
      cookie:
        same-site: none
        http-only: true
        secure: false
