spring:
  datasource:
    url: jdbc:h2:mem:monew;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
      schema-locations: classpath:schema-h2.sql

logging:
  level:
    root: DEBUG
    com.codeit.monew: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers  # dev에선 loggers 등 노출 허용
