spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/monew
    driver-class-name: org.postgresql.Driver
    username: monew_user
    password: monew1234
  data:
    mongodb:
      uri: ${SPRING_MONGODB_URL}
      port: 27017
      database: monew
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        default_schema: app

  sql:
    init:
      mode: never
      schema-locations: classpath:schema-postgres.sql

logging:
  level:
    root: DEBUG
    com.codeit.monew: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers  # dev에선 loggers 등 노출 허용
